name: Continuous Integration
jobs:
  run:
    name: Saas-reid
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: ['7.3', '7.4']
        phpunit-versions: ['latest']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.2'
            phpunit-versions: '8.5.13'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer install --no-progress no-suggest --prefer-dist --optimize-autoloader
      - name: Run PHP Code Sniffer
        run: php vendor/squizlabs/php_codesniffer/bin/phpcs
      - name: Run Acceptance Tests
        run : php  vendor/behat/behat/bin/behat --config behat.yaml
      - name: Run Tests
        run : php vendor/symfony/phpunit-bridge/bin/simple-phpunit --testsuite unit, integration